---
name: CI checks
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  maven-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        java: [8, 11, 15]
        jdk: [zulu, adopt]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.jdk }}
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}_jdk-${{ matrix.jdk }}-${{ matrix.java }}_maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}_jdk-${{ matrix.jdk }}-${{ matrix.java }}_maven-
      - name: Verify
        run: mvn -B verify
